/**
 * Anki Sync Api
 * Api for Anki Synchronization
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppConfiguration { 
    /**
     * The id of the last selected deck
     */
    curDeck: number;
    /**
     * The ids of the last selected deck and its sub-decks
     */
    activeDecks: Array<number>;
    /**
     * 0 - Mix new cards with reviews, 1 - New cards last, 2 - New cards first
     */
    newSpread: number;
    collapseTime: number;
    timeLim: number;
    estTimes: boolean;
    dueCounts: boolean;
    curModel: number;
    nextPos: number;
    sortType: string;
    sortBackwards: string;
    addToCur: boolean;
    dayLearnFirst: boolean;
    newBury: boolean;
    schedVer: number;
    rollover: number;
}

