/**
 * Anki Sync Api
 * Api for Anki Synchronization
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * authentication object used during the not-media synchronization
 */
export interface Auth { 
    /**
     * server-defined HostKey - used to authenticate the user
     */
    k: string;
    /**
     * app-defined SessionKey - used to identify the session
     */
    s: string;
}

