/**
 * Anki Sync Api
 * Api for Anki Synchronization
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelTemplate } from './model-template';
import { ModelField } from './model-field';


export interface Model { 
    sortf: number;
    did: number;
    latexPre: string;
    latexPost: string;
    latexsvg: boolean;
    mod: number;
    usn: number;
    type: number;
    css: string;
    name: string;
    flds: Array<ModelField>;
    tmpls: Array<ModelTemplate>;
    id: number;
    req: Array<Array<number | string | Array<number>>>;
}

