/**
 * Anki Sync Api
 * Api for Anki Synchronization
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostKeyAuth } from './host-key-auth';
import { Payload } from './payload';


export interface PayloadWithHostKeyAuth { 
    /**
     * GZip compression enabled
     */
    c: number;
    data: Blob;
    /**
     * server-defined HostKey - used to authenticate the user
     */
    k: string;
    v: string;
}

