/**
 * Anki Sync Api
 * Api for Anki Synchronization
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewCardConf { 
    bury: boolean;
    ease4: number;
    ivlFct: number;
    maxIvl: number;
    perDay: number;
    hardFactor: number;
}

